// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_Demo_1.Models;

namespace Project_Demo_1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250208064945_PlayerPhoto")]
    partial class PlayerPhoto
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project_Demo_1.Models.PlayerInfo", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PlayerAddress")
                        .IsRequired();

                    b.Property<int?>("PlayerAge")
                        .IsRequired();

                    b.Property<string>("PlayerName")
                        .IsRequired();

                    b.Property<int>("PlayerNoOfMatches");

                    b.Property<string>("PlayerPhotopath");

                    b.Property<int>("PlayerScore");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });
#pragma warning restore 612, 618
        }
    }
}
